language: python
python:
- 3.6
- 3.5
- 3.4
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: miguelgondu
  password:
    secure: NaQzACmluJJ27G+56prsXtFetPO65+m8VT3V1O80ejEVbc0HKS/7GhUPvEggJjwgmRRy3lMe7IaBPN5V0CjbiSgfDm5VIKDMLOI46KHPuUFcb85YTd6GwjjMh8Z4CFcUR6wrVTM7aS3jKAYhl1Z6K0wEyLihg3425Yx5rqFS6o2D77v0rQYMKKzhvTumaYwoXBfAK7OGCSFfGvXIFQJ3a4kLtuvTtHmSpcoj+xq9et/LrSZ4vfcZMqXMXvYdJnHSkirI3bUI4vs+HF0dtEVcZmLrw52Nub7YFEala8kE8IyYSTXa3LTHIP4gGorf3h9kz+h+U1iRnVaWUnQWXFQQBQei2xkstbOsrp2/sJ2rEZVOGy8/msCyddlqsz7u+6QOEMY0J5ebz5CuXlIO2wQ2fvyNyoC+MJqoRcjkeb1bZtQkfG+qOzRHKS4mkgXFyqElanzfgXiW3ZQsofA8Gxvzw1swwsB2GX6mIMTkZZocFBGE4r8gSc1Oj9yaDjeaVsIfM0addnbwk4n/M9KCkAsybLOaUQqGm/vVx/+KW+0A8K9neLklNI5hwRdbSqtnQpB72b7dpHMmff3C9VwSIWNx+/njHeREiiZhNeb0bienwfmwiIsLDBAqCVL0CLPcBwHoAbV6om4ZpxgKN2g0GeO8RmukS+PI7JmUWFV8uAWdkkk=
  on:
    tags: true
    repo: miguelgondu/generalrepytivity
    python: 3.6
