language: python
python:
- 3.6
- 3.5
- 3.4
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: miguelgondu
  password:
    secure: sTW+KmIzaGd694Y1IG8r6RZrk2KRLCkh7tADElbpycf0HvbtQ/R7ZY3OQZw5wddt3enCe+QwHv5Ycd7vpBrX2slq2wPoAkYitGi30YrsSM941znYBVwdD9SFB5msNOZBJMEL2ZuCZ49DcSkelBq8KtUau+CRLtESLZ1+LEq9TMMIkBrsc4pUMhHkY/YAy0HtYiSmSjt/vDslCPdEnRsg1SqlkiIY27D3VaY76prUo/wBz0zbSZE0glVzAGQagSIg9hZSurjAV04tRe7fSHBWAblW+7ZSCYu3u6dq096fuEYXeQ8AZ9xg2L+L0rAh9o5dEtJEKEy2oyl/3fjYUqfE/k3lNqtBu4Sk16rQBHmV8I611R5+z9fwTemZUGwA7kIHTVk8SWMMKVv8hXxIOXU1mZsi8P1MxJ6H33QhwI7cMXPkIHWtMp/GBw0hZQaKngI8k9j1yQRboG1Ubulao/kboLXvYP46MhVfqhxfSGZRJeELIkxnTpCDJGNSARApOXqguGceYds1LAvncncJRvcc9uWO2TWQmA8HLwXdIT7T2Gtvm0GPucnVW4JquPsIBDQ8yNyrzSxbLVXYVlJjz0KRb/rl9JHzOxs8AJx4RrGn76UTjOH37PZ4AWN4Y0XWLfCoZDk3UcNERre6uBz4geWs9aLVRZBEamZ/lVwngMsNSVQ=
  on:
    tags: true
    repo: miguelgondu/generalrepytivity
    python: 3.6
