language: python
python:
- 3.6
- 3.5
- 3.4
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: miguelgondu
  password:
    secure: f6dqWCS3WTCWkv78BQaYekzt+qH6Bfyk6x2IOVzdp+M8I64q2CJMtX2CcNX6JK6X5TKVK8ypkBtP6YqPUCqce9kx7UcKk0gKy+X8KNPeBP/ny5cMSE331KduY0dg0Iqqr11tmBU/ZC4XF+MSytOF9oc7rfBs6sa4ghn4v10+P1aSyAfBTs+cJHaQaHwsMo5/CeCGC+Yjf93uIv90uSWuGlUpNwYlMyAw82ioNb7Q7LPrTYZlgNJzio2GYPsqJdVy+kIcLKGHukFLbgl2FfMgOt3bOU/XylKbebisTT0ozSBeUC4djNPGLIOV3xog5L95PljU/twKNpWSvUXORipdWd/mv64IbMUeTenEG5T5mSJVNsp28Gswbmp6FNnurWYu4KQ5pOvu72QFLCzPxfGrh2vgfIrcHo/G99zo6+c3ECNlxaTAJ09JnpxU+JCm4L3r4NXiKGQ2kdsg6t4Yyewmpi2jcoIVCOTZ1nK4+wGCgjXS0SZsWJZFZe1gR15C5sPKaSKT6iMz35kBGPbmLhVxEBGVjsIzWAsX8RfRPlgQxI4rstLRCad+4GGWiwP1Exhh115q7FRL6nZn2289QEkrkGc+yBhj0xvxd8GprYEhb296xJhwaGpKyyOv/ImLbbhUcrNDCjZJQieyTyHDoummcI1EYfQ5kFexwdXE8xfmRiE=
  on:
    tags: true
    repo: miguelgondu/generalrepytivity
    python: 3.6
