language: python
python:
- 3.6
- 3.5
- 3.4
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: miguelgondu
  password:
    secure: "gNJNL38nke6Dqrb9VK1/bqHE9uy2yT+ussricUGdxtsx0tMXKGFmVQkOXRoOT89qr/1TBUTydAIi4Y/F2UZzo8jcQfSiFZNc+DpqoJY2cIrXdHh6Zqfn9ZAPV2r39kdN8e8vm627552hIGYuH0/wy9UWvSO/xZtyLJ6N7w+9i/HVr0pTez8taLEbObRAUNzmNQ6Je3GTrM6IXCF5S0EAjBT6XV4HG4d81EQoOWKMiLYB/rYkBhXIfNx4zzPriIEelS4AO9+hj+xAGG9kwezi0WRIJ905M4m7yOUL1DRfMTt1Ot1IDTFSw06SwWjcYOBF37ItWtIp0WCTKq8uuzyofBeIZA+f9yjqZbK2WjDjFP0lgfSPNG8EABDkb4JzALp1F8DS1ly60k3jOQJ8xK5CWDTP2GzskxmljukZYOo8mPAnGoObHDf8dXHFg1s2XLcMM8O7eN8wb4G2TKtq4rh3xc+cb/5LLjDCatiTO5Dt0keQvRjv5CsGZ1FN3+veF0CnW7TQdZxHrD09SXbpI4gOAwjxrxQ+tKtP2vCqNM8z/QB01rkSCl5L040nIUNOULMIRz9LxTeh0OYjqWqqhEfwt3X33gOpVvf57duRWFcUULSN/YV7rmw4DS7i+qAoO6DWxuNeaLP6K8ZDk2DO2c42Hb6qKcWUZUH2ZYkVfEt/7m8="
  on:
    tags: true
    repo: miguelgondu/generalrepytivity
    python: 3.6
