language: python
python:
- 3.6
- 3.5
- 3.4
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: "miguelgondu"
  password:
    secure: "18w638hO8jc2oPOiTQ3C/A81+ZQDRHesUv++SArkZtJjlVfmTykAqJ0qJTWaEiBgKHDY43O9J0Ezd7zvIHldGRyXBOHlX7zbZXO9aYMupMjX7a2BXBWz5TLqLt/uU1B6lgMRUU20JZqKwSL3xALl4Im+c2DRrcnA6qTpZMxkbPT6pE/kTmqRjf5R+j33Yn/xkD3emZ9hdiehU+XtcR/bdBwoFuPsKGCa5FNS6eFN8+BsnR8i04zihymRlJFk3rNBZr7UJ4J9gRm/GjZQsai8YzeduP7r6tpinFPpxuvKFAFyNnFYJQs5WYIxGGf1kNnoheIlOnne+J3FCpahyTGWQoVwtNujfj63leD7Ck08B3bpJpm8c9LZ5Db1wSiWjmFLSwTB3dIwDj9lGu0ZjsEcOu1nmaV7+dH9Xh3MHVa5ERUZfQV5LqTVTL54lKV5VN7fcozKsEZEHdHSKDEvKoDaJCeHdVZDL/tH9rvizfgjr/FHsetiWuCs7cUMNF5JyzX7RqPOLuTSFLXgX6r7ttAHwIzg1CGnqTp9FVthbdJu8AChcCpXPbB5a6no86j+gUxyQPDOZ4lgipsO2U2BK6zGzOEUWLslacSPvKXKChU1ncGhJRmi/0TzKjgm1El75rkDcAU0e4aaOdzd1PylSBMq9TmzobExgAqimaw2UUhsbMM="
  on:
    tags: true
    repo: miguelgondu/generalrepytivity
    python: 3.6
